# Generated by Django 3.1.6 on 2021-02-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelThemDau',
        ),
    ]
