# Generated by Django 3.0.5 on 2021-08-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
